# Generated by Django 2.1.2 on 2019-04-20 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_task', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskinfo',
            name='task_status',
            field=models.IntegerField(verbose_name='任务状态'),
        ),
    ]
