# Generated by Django 2.1.2 on 2019-04-22 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_task', '0003_taskinfo_task_sex_preference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskinfo',
            name='task_sex_preference',
            field=models.SmallIntegerField(default=0, verbose_name='性别要求'),
        ),
        migrations.AlterField(
            model_name='taskinfo',
            name='task_status',
            field=models.SmallIntegerField(verbose_name='任务状态'),
        ),
    ]
