# Generated by Django 2.1.2 on 2019-04-22 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_task', '0004_auto_20190422_0924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskacceptinfo',
            name='accept_user_evaluate',
            field=models.SmallIntegerField(null=True, verbose_name='领取者星级评价'),
        ),
        migrations.AlterField(
            model_name='taskacceptinfo',
            name='end_time',
            field=models.DateTimeField(null=True, verbose_name='完成时间'),
        ),
        migrations.AlterField(
            model_name='taskacceptinfo',
            name='initiate_user_evaluate',
            field=models.SmallIntegerField(null=True, verbose_name='发起者星级评价'),
        ),
    ]
