# Generated by Django 2.1.2 on 2020-03-09 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_task', '0005_auto_20190422_1834'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskCollectInfo',
            fields=[
                ('collect_id', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='收藏编号')),
                ('task_id', models.CharField(max_length=10, verbose_name='任务编号')),
                ('user_id', models.CharField(max_length=10, verbose_name='用户编号')),
                ('collect_time', models.DateTimeField(auto_now_add=True, verbose_name='评价时间')),
            ],
            options={
                'verbose_name_plural': '任务收藏信息',
                'verbose_name': '任务收藏信息',
                'db_table': 'task_collect',
            },
        ),
    ]
