# Generated by Django 2.1.2 on 2019-04-21 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='user_sex',
            field=models.IntegerField(verbose_name='用户性别'),
        ),
    ]
