# Generated by Django 2.1.2 on 2019-04-22 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_user', '0002_auto_20190421_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='user_authorization',
            field=models.SmallIntegerField(default=0, verbose_name='用户权限'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='user_sex',
            field=models.SmallIntegerField(verbose_name='用户性别'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='user_status',
            field=models.SmallIntegerField(default=0, verbose_name='用户账户状态'),
        ),
    ]
